# Membuat Logic Klasifikasi Single Layer Perceptron

In [1]:
import numpy as np

class SingleLayerPerceptron(object):
    def __init__(self,np_size,size):
        self.berat = np.zeros((size,np_size))
        self.bias = np.zeros(size)

    def get_berat(self):
        return (self.berat,self.bias)    
    
    def fungsi_aktivasi(self, v, threshold):
        if threshold >= v and v >= -(threshold):
            return 0
        elif v > threshold:
            return 1
        else:
            return -1
    
    def train(self,train_data,train_target,threshold):
        epoch = 1
        stop = False
        while stop is False:
            stop = True
            print("EPOCH ", epoch,end = '\n' )
            for i in range(len(train_data)):
                v = np.zeros(len(train_target))
                y = np.zeros(len(train_target))
                for j in range(len(train_target)):
                    v[j] = np.dot(train_data[i], self.berat[j]) + self.bias[j]
                    y[j] = self.fungsi_aktivasi(v[j], threshold)
                    print("v index ",j,": ",v[j])
                    print("y index ",j,": ",y[j])
                    if y[j] != train_target[i][j]:
                        self.berat[j] = self.berat[j] + (train_target[i][j] * train_data[i])
                        self.bias[j] = self.bias[j] + train_target[i][j]
                        stop = False
                    print('------------------------------------------------------------------------------------')

            epoch += 1
            (PrintBerat,PrintBias) = self.get_berat()
            print("berat: ",PrintBerat)
            print("bias: ",PrintBias)
            print("kondisi berhenti: ", stop)
            print('====================================================================================', end = '\n\n')

    def test(self, test_data, threshold):
        v = np.zeros(len(self.berat))
        y = np.zeros(len(self.berat))
        for i in range(len(self.berat)):
            v[i] = np.dot(test_data, self.berat[i]) + self.bias[i]
            y[i] = self.fungsi_aktivasi(v[i], threshold)
        return y

# Membuat Method Untuk Mengkonversi Inputan Gambar Menjadi Numeric

In [2]:
def huruf2array(huruf):
    huruf=huruf.replace("#","1,").replace(".","0,").replace("\n",'')
    arr = np.fromstring(huruf[:-1],dtype=int,sep=',')
    return arr

file = open("data/input_latih1_huruf_a.txt", 'r')
x = file.read()
file.close()
print("Hasil Numeric Data Latih Huruf A: ")
print(huruf2array(x))

Hasil Numeric Data Latih Huruf A: 
[0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 1
 1 1 1 1 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 1 1 1 0 1 1 1]


# Membuat Method Untuk Cek Huruf

In [3]:
def cekHuruf(hasil):
    if np.array_equal(hasil, np_dataTrain[0]):
        return "a",hasil
    elif np.array_equal(hasil, np_dataTrain[1]):
        return "b",hasil
    elif np.array_equal(hasil, np_dataTrain[2]):
        return "c",hasil
    else:
        return "undefined",hasil

# Mendefinisi Data Latih dan Targetnya

In [4]:
# Read all data
file = open("data/list_data_latih.txt", 'r')
listDataLatih = file.read()
file.close()

arrDataLatih = listDataLatih.replace("\n", ",").split(',')

dataLatih = []
for namafile in arrDataLatih:
    file = open("data/" + namafile, 'r')
    huruf = file.read()
    dataLatih.append(huruf2array(huruf))
    
dataLatih = np.array(dataLatih)
print("Data Train: ")
print(dataLatih, end = '\n\n')

#Data Target Training
huruf_a = [1, -1, -1]
huruf_b = [-1, 1, -1]
huruf_c = [-1, -1, 1]

dataTrain = [huruf_a, huruf_b, huruf_c]

np_dataTrain=np.array(dataTrain)
print("Data Train Target: ")
print(np_dataTrain)

Data Train: 
[[0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0
  1 1 1 1 1 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 1 1 1 0 1 1 1]
 [1 1 1 1 1 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 1 1 1 0 0
  1 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
  0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 1 0]]

Data Train Target: 
[[ 1 -1 -1]
 [-1  1 -1]
 [-1 -1  1]]


# Melakukan Training Pada Model Single Layer Perceptron

In [5]:
#training data

data = dataLatih
target = np.array(dataTrain)
threshold = 0
slp = SingleLayerPerceptron(63,3)
slp.train(data,target,threshold)

(bobot,bias)=slp.get_berat()

EPOCH  1
v index  0 :  0.0
y index  0 :  0.0
------------------------------------------------------------------------------------
v index  1 :  0.0
y index  1 :  0.0
------------------------------------------------------------------------------------
v index  2 :  0.0
y index  2 :  0.0
------------------------------------------------------------------------------------
v index  0 :  12.0
y index  0 :  1.0
------------------------------------------------------------------------------------
v index  1 :  -12.0
y index  1 :  -1.0
------------------------------------------------------------------------------------
v index  2 :  -12.0
y index  2 :  -1.0
------------------------------------------------------------------------------------
v index  0 :  -7.0
y index  0 :  -1.0
------------------------------------------------------------------------------------
v index  1 :  7.0
y index  1 :  1.0
------------------------------------------------------------------------------------
v index  2 :  

# Melakukan Testing Pada Data Latih & Data Uji

In [6]:
#data uji
file = open("data/list_data_uji.txt", 'r')
dataset_uji = file.read()
file.close()

dataset_uji = dataset_uji.replace("\n", ",")
arrDataUji = dataset_uji.split(',')


dataUji = []
for namafile in arrDataUji:
    file = open("data/" + namafile, 'r')
    huruf = file.read()
    dataUji.append(huruf2array(huruf))
    
dataUji = np.array(dataUji)
print("Hasil Testing Dengan Data Latih: ")
for index, data_latih in enumerate(dataLatih):
    print("data latih", index, end=" : ")
    hasil_latih = slp.test(data_latih, threshold)
    print(cekHuruf(hasil_latih))
    
print('')
print("Hasil Testing Dengan Data Uji: ")
for index, data_uji in enumerate(dataUji):
    print("data uji", index, end=" : ")
    hasil_uji = slp.test(data_uji, threshold)
    print(cekHuruf(hasil_uji))

Hasil Testing Dengan Data Latih: 
data latih 0 : ('a', array([ 1., -1., -1.]))
data latih 1 : ('b', array([-1.,  1., -1.]))
data latih 2 : ('c', array([-1., -1.,  1.]))

Hasil Testing Dengan Data Uji: 
data uji 0 : ('a', array([ 1., -1., -1.]))
data uji 1 : ('undefined', array([-1., -1., -1.]))
data uji 2 : ('c', array([-1., -1.,  1.]))
